import Head from "next/head";
import Image from "next/image";
import scenario_gif from "../files/gifs/NameScreen.gif";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center bg-black text-dark min-w-screen">
          <div className="flex items-center justify-center w-full">
              <Image
                src={scenario_gif}
                alt="task allocation gif"
                className="w-auto h-full"
              />
          </div>
      </main>
    </>
  )
}
